<?php

namespace AppBundle\Repository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUsernameYear($username, $year) {

        $em = $this->getEntityManager();

        $dql = '
            SELECT c
            FROM AppBundle:Calendar c
              INNER Join c.user u
            WHERE u.username LIKE :username
              AND c.year = :year
        ';

        $query = $em->createQuery($dql);
        $query->setParameter('username', $username);
        $query->setParameter('year', $year);

        return $query->getResult();

    }
}
