<?php

namespace AppBundle\Repository;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUsername($username) {

        $em = $this->getEntityManager();

        $dql = "
            SELECT c
            FROM AppBundle:Calendar c
            WHERE c.username = :username
        ";

        $query = $em->createQuery($dql);
        $query->setParameter('username', $username);

        return $query->getResult();

    }
}
