<?php

namespace AppBundle\Repository;

/**
 * EventHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
