<?php

/*
 *     Iker Ibarguren <@ikerib>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getEvents($calendarid)
    {
        $em = $this->getEntityManager();
        /** @var $query \Doctrine\DBAL\Query\QueryBuilder */
        $query = $em->createQuery('
            SELECT e
                FROM AppBundle:Event e 
                  LEFT JOIN e.calendar c
                WHERE c.id = :calendarid
        ');

        //$consulta = $em->createQuery($dql);
        $query->setParameter('calendarid', $calendarid);

        return $query->getResult();
    }

    public function findCalendarSelfEvents($calendarid) {

        // TODO: Remove hardcoded type id

        $em = $this->getEntityManager();
        /** @var $query \Doctrine\DBAL\Query\QueryBuilder */
        $query = $em->createQuery('
            SELECT e
                FROM AppBundle:Event e 
                  LEFT JOIN e.calendar c
                WHERE c.id = :calendarid
                AND e.type = 5
        ');

        $query->setParameter('calendarid', $calendarid);

        return $query->getResult();
    }

}
