<?php

namespace AppBundle\Repository;

/**
 * FirmadetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmadetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFirmatuaDutenErabiltzaileak($firmaid) {
        $qm = $this->createQueryBuilder( 'fd' )
            ->innerJoin( 'fd.firma','f')
            ->where( 'f.id = :firmaid' )
            ->setParameter('firmaid', $firmaid)
        ;


        return $qm->getQuery()->getResult();
    }
}
