<?php

namespace AppBundle\Repository;

/**
 * FirmadetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FirmadetRepository extends \Doctrine\ORM\EntityRepository
{
}
