<?php

namespace AppBundle\Repository;

/**
 * IkastaroaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IkastaroaRepository extends \Doctrine\ORM\EntityRepository
{
}
