<?php

namespace AppBundle\Repository;

/**
 * KonpentsatuakRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KonpentsatuakRepository extends \Doctrine\ORM\EntityRepository
{
}
