<?php

namespace AppBundle\Repository;

/**
 * KuadranteaEskaerekinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KuadranteaEskaerekinRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserYearMonth($userid, $year, $hilabetea)
    {
        $qb = $this->createQueryBuilder('k')
            ->andWhere('k.user = :userid')->setParameter('userid', $userid)
            ->andWhere('k.urtea = :year')->setParameter('year', $year)
            ->andWhere('k.hilabetea = :hilabetea')->setParameter('hilabetea', $hilabetea);

        return $qb->getQuery()->getResult();
    }

    public function findallSaila($sailaid) {
        $qb = $this->createQueryBuilder('k')
            ->select('k')
            ->join('k.user', 'u')
            ->andWhere('u.saila=:sailaid')->setParameter('sailaid', $sailaid)

        ;
        return $qb->getQuery()->getResult();
    }
}
