<?php

namespace AppBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserUnreadMessages($userid)
    {
        $qb = $this->_em->createQueryBuilder()
                        ->select('m')
                        ->from('AppBundle:Message', 'm')
                        ->where('m.readed=0');


        return $qb->getQuery()->getResult();
    }
}
