<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{

    public function getAllUnreadSortedByUser() {
        /** @var QueryBuilder $qb */
        $qb = $this->createQueryBuilder('n')
            ->innerJoin('n.user', 'u')
            ->andWhere('n.readed=false')
            ->orderBy('n.user')
        ;

        return $qb->getQuery()->getResult();
    }

    public function getAllUnread($userid) {
        /** @var QueryBuilder $qb */
        $qb = $this->createQueryBuilder('n')
            ->innerJoin('n.user', 'u')
            ->where('u.id=:userid')
            ->andWhere('n.readed=false')
            ->setParameter('userid',$userid)
        ;

        return $qb->getQuery()->getResult();
    }

    public function getCurrentUserNotifications($userid, $q) {

        $qb = $this->createQueryBuilder( 'n' )
            ->innerJoin( 'n.user', 'u' )
            ->where( 'u.id=:userid' )
            ->setParameter( 'userid', $userid );

        if ($q) {

            if ($q == 'unread' ) {
                $qb->andWhere( 'n.readed=false' );
            } elseif ($q == 'readed') {
                $qb->andWhere( 'n.readed=true' );
            } elseif ($q == 'unanswered') {
                $qb->andWhere( 'n.result=false' );
            }

        }



        return $qb->getQuery()->getResult();
    }

}
