<?php

namespace AppBundle\Repository;

/**
 * SinatzaileakdetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SinatzaileakdetRepository extends \Doctrine\ORM\EntityRepository
{
}
