<?php

namespace AppBundle\Repository;

/**
 * TempEskaerakEgutegianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempEskaerakEgutegianRepository extends \Doctrine\ORM\EntityRepository
{
}
