<?php

namespace AppBundle\Repository;

/**
 * TemplateEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateEventRepository extends \Doctrine\ORM\EntityRepository
{
}
