<?php

namespace AppBundle\Repository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByOrder() {
        $em = $this->getEntityManager();
        /** @var  $query \Doctrine\DBAL\Query\QueryBuilder */
        $query = $em->createQuery("
            SELECT t
                FROM AppBundle:Type t
                ORDER BY t.orden
        ");


        return $query->getResult();
    }
}
